site_name: BCIT Learning Hub Documentation
nav:
  - Home: index.md
  - Task 1: task1.md
  - Task 2: task2.md
  - Task 3: task3.md
  - Troubleshooting: troubleshoot.md
  - Glossary: glossary.md
theme:
  name: material
markdown_extensions:
  - attr_list
  - attr_list
  - md_in_html
