site_name: BCIT Learning Hub Documentation
nav:
  - Home: index.md
  - Enrolling into Groups: task1.md
  - Submitting Assignment: task2.md
  - Creating Discussion Thread: task3.md
  - Troubleshooting: troubleshoot.md
  - Glossary: glossary.md

theme:
  name: material
  features:
    - toc.integrate

markdown_extensions:
  - attr_list
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
